-- Вход в кабинет партнёра: партнёру нужен числовой id для серверных сессий
-- (sessions.user_id — bigint). PK партнёра остаётся code (на него завязаны
-- orders.ref, partner_clicks, partner_payouts) — id добавляем как суррогат.

ALTER TABLE partners
  ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX IF NOT EXISTS partners_id_uidx ON partners (id);
